pipeline {
  agent any
  tools { nodejs 'NodeJs'}       
  environment {
    CI = 'true'
    REACT_APP_API_BASE_URL = credentials('api-base-url')
    REGISTRY = 'kkattlacrjenkins.azurecr.io'              
    IMAGE    = "${REGISTRY}/schedule_app_kkatl"     
    TAG      = "${env.BUILD_NUMBER}-${env.GIT_COMMIT?.substring(0,7) ?: 'dev'}"
  }

  stages {
    stage('Checkout') {
      steps { checkout scm }
    }

    stage('Install') {
      steps {
        dir('frontend/frontend') {
          sh 'npm install --cache $HOME/.npm --prefer-offline'
        }
      }
    }

    stage('Build') {
      steps {
        dir('frontend/frontend') {
          sh 'npm run build && zip -r build.zip build'
        }
      }
    }

    stage('Docker image') {
  steps {
    dir('frontend') {
      withEnv(["PATH+DOCKER=/Applications/Docker.app/Contents/Resources/bin"]) {        
        withCredentials([usernamePassword(
            credentialsId: 'acr-admin-creds',
            usernameVariable: 'USER',
            passwordVariable: 'PASS')]) {

          sh '''
            echo $PASS | docker login $REGISTRY -u $USER --password-stdin
            docker build -t $IMAGE:$TAG -t $IMAGE:latest -f Dockerfile .
            docker push  $IMAGE:$TAG
            docker push  $IMAGE:latest
          '''
        }
      }
    }
  }
}

  }

  post {
    success {
      archiveArtifacts artifacts: 'frontend/frontend/build.zip', fingerprint: true
    }
  }
}
