
pipeline {
  agent any
  tools { 
    jdk    'jdk'
    gradle 'gradle'
  }
  environment {
    SONAR_SERVER = 'sqs'
    REGISTRY = 'kkattlacrschedule.azurecr.io'              
    IMAGE    = "${REGISTRY}/schedule_backend_kkattl"  
    TAG      = "${BUILD_NUMBER}-${GIT_COMMIT?.substring(0,7) ?: 'dev'}"
  }

  stages {
    stage('Checkout') {
      steps { checkout scm }
    }

    stage('Build') {
      steps {
        dir('backend/backend') {
          sh 'gradle clean build --no-daemon'
        }
      }
      post {
        always {
          junit 'backend/backend/build/test-results/**/*.xml'
        }
      }
    }

    stage('SonarQube Analysis') {
      steps {
        dir('backend/backend') {
          withCredentials([string(credentialsId: 'sonar', variable: 'SONAR_TOKEN')]) {
            withSonarQubeEnv("${SONAR_SERVER}") {
              sh 'gradle sonarqube --no-daemon -Dsonar.login=$SONAR_TOKEN'
            }
          }
        }
      }
    }


    stage('Quality Gate') {
      steps {
        script {
          def task = sh(
            script: "curl -s 'http://localhost:9000/api/ce/task?id=${env.SONAR_TASK_ID}'",
            returnStdout: true
          )
        }
      }
    }


    
    stage('Docker Build & Push') {
      steps {
        dir('backend') {                      
          withEnv(["PATH+DOCKER=/usr/local/bin"]) {
            withCredentials([
              usernamePassword(
                credentialsId: 'acr-admin-creds',
                usernameVariable: 'ACR_USER',
                passwordVariable: 'ACR_PASS'
              ),
              usernamePassword(
                credentialsId: 'postgres-creds',
                usernameVariable: 'DB_USER',
                passwordVariable: 'DB_PASS'
              ),
              string(credentialsId: 'postgres-host', variable: 'DB_HOST'),
              string(credentialsId: 'redis-host',    variable: 'REDIS_HOST')
            ]) {

              sh '''
                echo $ACR_PASS | docker login $REGISTRY -u $ACR_USER --password-stdin

                docker build --platform linux/amd64 \
                  --build-arg DATABASE=$DB_NAME \
                  --build-arg USERNAME=$DB_USER \
                  --build-arg USERPASSWORD=$DB_PASS \
                  --build-arg POSTGRES_HOST=$DB_HOST \
                  --build-arg REDIS_HOST=$REDIS_HOST \
                  -t $IMAGE:$TAG -t $IMAGE:latest \
                  -f Dockerfile .

                docker push $IMAGE:$TAG
                docker push $IMAGE:latest
              '''
            }
          }
        }
      }
    }

    stage('Deploy via Ansible') {
      environment {
        PATH = "/opt/homebrew/bin:${env.PATH}"
      }
      steps {
        withCredentials([
          usernamePassword(
          credentialsId: 'azure-sp-creds',
          usernameVariable: 'AZURE_CLIENT_ID',
          passwordVariable: 'AZURE_CLIENT_SECRET'
        ),
        string(
          credentialsId: 'azure-tenant-id',
          variable: 'AZURE_TENANT_ID'
        ),
        string(
          credentialsId: 'azure-subscription-id',
          variable: 'AZURE_SUBSCRIPTION_ID'
        )
          ]) {
            withCredentials([
              file(credentialsId: 'ansible-inventory', variable: 'INV_FILE')
            ]) {
              sh '''
                set -e
                az login --service-principal -u $AZURE_CLIENT_ID -p $AZURE_CLIENT_SECRET --tenant $AZURE_TENANT_ID
                az account set --subscription $AZURE_SUBSCRIPTION_ID
                export ANSIBLE_CONFIG=ansible/ansible.cfg
                ansible-playbook -i "$INV_FILE" ansible/deploy_backend.yml --extra-vars "image_tag=${TAG}"
              '''
          }
        }
      }
     }
  }

  post {
    success { echo "Done: ${IMAGE}:${TAG}" }
    failure { echo "Failed – check logs." }
  }
}
