- name: Start Bastion tunnels
  shell: |
    az network bastion tunnel \
      --name {{ bastion_name }} \
      --resource-group {{ resource_group }} \
      --target-resource-id $(az vm show -g {{ resource_group }} -n {{ item.vm_name }} --query id -o tsv) \
      --resource-port 22 \
      --port {{ item.local_port }} \
      --timeout 3600
  loop: "{{ bastion_targets }}"
  loop_control:
    label: "{{ item.vm_name }}"
  async: 3605
  poll: 0

- name: Pause briefly for tunnels to establish
  pause:
    seconds: 5