- name: Log in to ACR
  community.docker.docker_login:
    registry_url: "{{ acr_login_server }}"
    username:     "{{ acr_username }}"
    password:     "{{ acr_password }}"

- name: Gather existing container info
  community.docker.docker_container_info:
    name: "{{ container_name }}"
  register: existing_container
  failed_when: false

- name: Stop and remove existing container
  community.docker.docker_container:
    name:       "{{ container_name }}"
    state:      absent
    force_kill: yes
  when: existing_container.exists

- name: Pull image from ACR with platform support
  ansible.builtin.shell: >
    docker pull --platform linux/amd64 {{ acr_login_server }}/{{ image_name }}:{{ image_tag }}

- name: Run new container
  community.docker.docker_container:
    name:           "{{ container_name }}"
    image:          "{{ acr_login_server }}/{{ image_name }}:{{ image_tag }}"
    state:          started
    restart_policy: "{{ restart_policy | default('always') }}"
    published_ports: "{{ container_ports }}"
