version: '3'

services:
  postgres:
    image: postgres:13
    container_name: sonarqube-postgres
    environment:
      POSTGRES_USER: sonar
      POSTGRES_PASSWORD: sonar
      POSTGRES_DB: sonar
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - sonarnet
    restart: unless-stopped

  sonarqube:
    image: sonarqube:community
    container_name: sonarqube
    depends_on:
      - postgres
    ports:
      - "9000:9000"
    environment:
      SONAR_JDBC_URL: jdbc:postgresql://postgres:5432/sonar
      SONAR_JDBC_USERNAME: sonar
      SONAR_JDBC_PASSWORD: sonar
    volumes:
      - sonarqube-data:/opt/sonarqube/data
      - sonarqube-extensions:/opt/sonarqube/extensions
      - sonarqube-logs:/opt/sonarqube/logs
    networks:
      - sonarnet
    restart: unless-stopped
    ulimits:
      nofile:
        soft: 65536
        hard: 65536

networks:
  sonarnet:
    driver: bridge

volumes:
  postgres-data:
  sonarqube-data:
  sonarqube-extensions:
  sonarqube-logs:
