- name: Open Bastion tunnel
  hosts: bastion
  connection: local
  gather_facts: false 
  roles:
    - bastion

- name: Deploy Frontend via ACR image
  hosts: backend
  become: true
  gather_facts: false
  collections:
    - community.docker
  roles:
    - docker_deploy
